### ISSUE TITLE
[Enhancement] Spotify Integration

### ISSUE THREAD

**Issue by TharathielCB** [pirateradiohack/PiRadio#8]
Would it be possible to integrate the spotify connect feature from raspotify?
https://github.com/dtcooper/raspotify

**Comment by pirateradiohack** [comment]
Thanks for the suggestion. I think it should be possible.

I do not plan to do it at the moment though, as my scope is really about web radios.  
Spotify is well supported by other popular audio projects. I believe [Volumio](https://volumio.com/en/get-started/) is one of them.
